name: UHCWars
version: 0.8.1
author: NoReach
main: me.noreach.uhcwars.UHCWars
commands:
  region:
  setlocation:
  objective:
  kit:
  statistics:
    aliases: [stats]
  world:
  teamchat:
    aliases: [tc, teamc, chat]
  moderation:
    aliases: [mod]